### ISSUE TITLE
Comprehensive guide how to sync the sonic

### ISSUE THREAD

**Issue by m-e-m-f-i-s-19** [Fantom-foundation/Sonic#139]
I used **full mpt** genesis file: https://download.fantom.network/mainnet-109331-full-mpt.g  and it took several days to read it and import to carmen but now it has to sync 2 years period. Is this how it supposed to work? Could you please confirm that or update documentation about how to setup sonic node.

Could you please, update the documentation how to start sonic node correctly.  Also would be nice to have updated snapshot.

**Comment by janzhanal** [comment]
I did try to run from snapshot from https://snapshot-trace.fantom.network/files/sonic/snapshot-27-May-2024-04-29/ and failed with 
```
failed to initialize the node: failed to make consensus engine: failed to open EvmStore: starting node with enabled archive (rpc mode), but the archive database does exists - terminated to avoid creating an inconsistent archive database (re-apply genesis and resync the node to switch to archive configuration)
```
 so I would also appreciate a bit of docu to start the node...

**Comment by Sleapy31** [comment]
All effort is put on shilling random numbers on twitter instead of facilitate node syncing

**Comment by thaarok** [comment]
Sonic use a different format for genesis files - they are now available to download from https://download.fantom.network/ - use the "Sonic Genesis Files".

Legacy genesis file can be used as a fallback, but only the full-mpt version - I don't recommend.
Updating the documentation is in progress.

**Comment by janzhanal** [comment]
Hello @thaarok, 
thank you for your point unfortunately it does not work:

```
root@ovh-us-hi-26:/go# sonictool --cache 64226 --datadir=/data genesis /data/mainnet-285300-archive.g
genesis file check failed: genesis file doesn't refer to any trusted preset
root@ovh-us-hi-26:/go# sonictool --cache 64226 --datadir=/data genesis /data/mainnet-5577-archive.g 
genesis file check failed: genesis file doesn't refer to any trusted preset
```

**Comment by thaarok** [comment]
@janzhanal please use up-to-date Sonic client version 1.2.1-c

**Comment by janzhanal** [comment]
yes, that helped, thank you
