### ISSUE TITLE
Can not sync snapshot

### ISSUE THREAD

**Issue by alexandersazonof** [Fantom-foundation/Sonic#150]
**Describe the bug**
Hello, I try to sync node with snapshot, but got error:
```
Fantom World State Live data not available in the genesis module=gossip-store err="hashes root not found"
```

**To Reproduce**
1. ./sonictool --datadir="/home/fantom/data" --cache 16000 genesis mainnet-171200-pruned-mpt.g
2. After sync I see error in logs

**Comment by thaarok** [comment]
Use new "Sonic Genesis Files" from https://download.fantom.network/

Legacy genesis file can be used as a fallback, but only the full-mpt version - I don't recommend.
Updating the documentation is in progress.
