### ISSUE TITLE
Can not run after client after shutdown

### ISSUE THREAD

**Issue by alexandersazonof** [Fantom-foundation/Sonic#158]
After shutdown I got error: 

```
failed to initialize the node: failed to make consensus engine: failed to open existing databases: dirty state: gossip: DE
```

**Comment by thaarok** [comment]
This happens when you kill the process forcefully, before it can close the database.
When stopping Sonic, make sure to wait until it produce this log message:
```
INFO [05-15|17:36:10.855] State DB closed                          module=evm-store
```

**Comment by alexandersazonof** [comment]
If I need to run the Sonic client again, what should I do?

**Comment by pc-quiknode** [comment]
Is there a way to repair the db from broken state?
